pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:8.0'
        }
    }

    stages {
        stage('Checkout') { 
            steps {
                git url: 'https://github.com/ImaneDKHISSI/JenkinsProjet.git', branch: 'main'
            }
        }

        stage('Restore Dependencies') { 
            steps {
                sh 'dotnet restore ProjetJenkins.sln'
            }
        }

        stage('Build') { 
            steps {
                sh 'dotnet build ProjetJenkins.sln --no-restore'
            }
        }

        stage('Test') { 
            steps {
                sh 'dotnet test TestUnitaire/TestUnitaire.csproj --no-build'
            }
        }

        stage('Publish') { 
            steps {
                sh 'dotnet publish ProjetJenkins/ProjetJenkins.csproj -c Release -o out'
            }
        }
    }

    post {
        success {
            echo 'Pipeline exécuté avec succès !'
        }
        failure {
            echo 'Le pipeline a échoué.'
        }
    }
}
